server:
  port: 8081


spring:

  datasource:
    url: jdbc:mysql://localhost:3306/video?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段
      logic-delete-value: 1 # 已删除(1)
      logic-not-delete-value: 0 # 未删除(0)
